"""Model & provider catalog — prices, capabilities and sovereignty metadata.

The catalog ships as ``catalog.json`` next to this module and is generated by
``scripts/build_catalog.py`` from the LiteLLM price map plus a curated list of
models and providers. Price and capability field names are LiteLLM's, so the
two can be diffed directly.

Sovereignty fields (``jurisdiction``, ``us_cloud_act_exposure``, ``zdr`` ...)
are ``None`` when unknown. Callers enforcing a data policy must treat ``None``
as "not compliant", never as "compliant".
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from types import MappingProxyType
from typing import Any, Mapping

DEFAULT_CATALOG_PATH = Path(__file__).with_name("catalog.json")
SUPPORTED_SCHEMA_VERSION = 1

# Providers echo dated snapshots ("gpt-4o-2024-08-06", "claude-x-20250929")
# for undated requests; strip the suffix to find the base model.
_DATE_SUFFIX = re.compile(r"-(?:\d{4}-\d{2}-\d{2}|\d{8})$")


def strip_date_suffix(model: str) -> str:
    return _DATE_SUFFIX.sub("", model)


@dataclass(frozen=True)
class ProviderInfo:
    id: str
    name: str
    provider_hq_country: str | None
    jurisdiction: str | None
    us_cloud_act_exposure: bool | None
    hosting_countries: tuple[str, ...] | None
    zdr: bool | None
    certifications: tuple[str, ...] | None
    openai_compatible: bool
    base_url: str | None
    sovereign_supply: bool
    notes: str | None = None


@dataclass(frozen=True)
class ModelInfo:
    vendor: str
    model: str
    provider: ProviderInfo
    pricing: Mapping[str, float]
    capabilities: Mapping[str, Any]
    aliases: tuple[str, ...] = ()
    deprecation_date: str | None = None
    source: str = "litellm"

    @property
    def id(self) -> str:
        return f"{self.vendor}/{self.model}"

    @property
    def input_cost_per_token(self) -> float | None:
        return self.pricing.get("input_cost_per_token")

    @property
    def output_cost_per_token(self) -> float | None:
        return self.pricing.get("output_cost_per_token")

    def supports(self, capability: str) -> bool:
        """True only when the catalog affirmatively lists the capability."""
        return self.capabilities.get(f"supports_{capability}") is True


@dataclass(frozen=True)
class Catalog:
    version: str
    providers: Mapping[str, ProviderInfo]
    models: Mapping[str, ModelInfo]
    _index: Mapping[tuple[str, str], ModelInfo] = field(repr=False, default_factory=dict)

    def get(self, vendor: str, model: str | None) -> ModelInfo | None:
        """Look up a model by exact name, alias, then date-stripped name."""
        if not model:
            return None
        hit = self._index.get((vendor, model))
        if hit is None:
            hit = self._index.get((vendor, strip_date_suffix(model)))
        return hit

    def pricing_table(self) -> dict[tuple[str, str], tuple[float, float]]:
        """Legacy ``(vendor, model) -> (input_per_1k, output_per_1k)`` table.

        Includes aliases. Models without both base prices are left out, so
        ``estimate_cost`` reports them as unmetered (None).
        """
        table: dict[tuple[str, str], tuple[float, float]] = {}
        for (vendor, name), m in self._index.items():
            in_rate, out_rate = m.input_cost_per_token, m.output_cost_per_token
            if in_rate is None or out_rate is None:
                continue
            table[(vendor, name)] = (round(in_rate * 1000, 12), round(out_rate * 1000, 12))
        return table


def _provider(pid: str, raw: dict) -> ProviderInfo:
    def tup(v):
        return tuple(v) if v is not None else None

    return ProviderInfo(
        id=pid,
        name=raw["name"],
        provider_hq_country=raw.get("provider_hq_country"),
        jurisdiction=raw.get("jurisdiction"),
        us_cloud_act_exposure=raw.get("us_cloud_act_exposure"),
        hosting_countries=tup(raw.get("hosting_countries")),
        zdr=raw.get("zdr"),
        certifications=tup(raw.get("certifications")),
        openai_compatible=bool(raw.get("openai_compatible", False)),
        base_url=raw.get("base_url"),
        sovereign_supply=bool(raw.get("sovereign_supply", False)),
        notes=raw.get("notes"),
    )


def parse_catalog(data: dict) -> Catalog:
    """Validate and index a catalog document (the parsed ``catalog.json``)."""
    version = data.get("schema_version")
    if version != SUPPORTED_SCHEMA_VERSION:
        raise ValueError(
            f"Unsupported catalog schema_version {version!r}; "
            f"expected {SUPPORTED_SCHEMA_VERSION}"
        )
    providers = {pid: _provider(pid, raw) for pid, raw in data["providers"].items()}

    models: dict[str, ModelInfo] = {}
    index: dict[tuple[str, str], ModelInfo] = {}
    for model_id, raw in data["models"].items():
        vendor = raw["vendor"]
        if vendor not in providers:
            raise ValueError(f"{model_id}: unknown provider {vendor!r}")
        m = ModelInfo(
            vendor=vendor,
            model=raw["model"],
            provider=providers[vendor],
            pricing=MappingProxyType(dict(raw.get("pricing", {}))),
            capabilities=MappingProxyType(dict(raw.get("capabilities", {}))),
            aliases=tuple(raw.get("aliases", ())),
            deprecation_date=raw.get("deprecation_date"),
            source=raw.get("source", "litellm"),
        )
        models[model_id] = m
        for name in (m.model, *m.aliases):
            if (vendor, name) in index:
                raise ValueError(f"{vendor}/{name}: listed twice in the catalog")
            index[(vendor, name)] = m

    return Catalog(
        version=data["catalog_version"],
        providers=MappingProxyType(providers),
        models=MappingProxyType(models),
        _index=MappingProxyType(index),
    )


def load_catalog(path: str | Path | None = None) -> Catalog:
    """Load a catalog file; with no path, the bundled one (cached)."""
    if path is None:
        return _bundled()
    return parse_catalog(json.loads(Path(path).read_text(encoding="utf-8")))


@lru_cache(maxsize=1)
def _bundled() -> Catalog:
    return parse_catalog(json.loads(DEFAULT_CATALOG_PATH.read_text(encoding="utf-8")))
